"""Curated seed books for the Lounge recommendation pipeline."""
from __future__ import annotations


SEED_BOOKS: list[dict] = [
    {
        "book_id": "seed_demian",
        "isbn13": "9788937460449",
        "title": "데미안",
        "author": "헤르만 헤세",
        "publisher": "민음사",
        "published_date": "2009",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9788937460449-L.jpg",
        "description": "자기 안의 목소리를 따라 성장해가는 청년의 내면 여정을 그린 고전 소설입니다.",
        "category": "문학",
        "sub_category": "성장소설",
        "rating": 4.7,
        "review_count": 23451,
        "source": "seed",
        "source_url": "",
    },
    {
        "book_id": "seed_cosmos",
        "isbn13": "9788983710871",
        "title": "코스모스",
        "author": "칼 세이건",
        "publisher": "사이언스북스",
        "published_date": "2006",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9788983710871-L.jpg",
        "description": "우주와 인간의 관계를 과학, 역사, 철학의 언어로 넓게 이어 보이는 지적 탐험입니다.",
        "category": "과학",
        "sub_category": "교양과학",
        "rating": 4.8,
        "review_count": 9234,
        "source": "seed",
        "source_url": "",
    },
    {
        "book_id": "seed_prince",
        "isbn13": "9788954622936",
        "title": "어린 왕자",
        "author": "앙투안 드 생텍쥐페리",
        "publisher": "문학동네",
        "published_date": "2015",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9788954622936-L.jpg",
        "description": "관계, 책임, 순수함을 짧고 투명한 이야기로 다시 생각하게 하는 우화입니다.",
        "category": "문학",
        "sub_category": "우화",
        "rating": 4.9,
        "review_count": 45231,
        "source": "seed",
        "source_url": "",
    },
    {
        "book_id": "seed_sapiens",
        "isbn13": "9788934972464",
        "title": "사피엔스",
        "author": "유발 하라리",
        "publisher": "김영사",
        "published_date": "2015",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9788934972464-L.jpg",
        "description": "인류가 어떻게 세계를 만들고 믿음과 제도로 서로를 묶어왔는지 큰 시야로 해석합니다.",
        "category": "인문",
        "sub_category": "역사",
        "rating": 4.6,
        "review_count": 12847,
        "source": "seed",
        "source_url": "",
    },
    {
        "book_id": "seed_1984",
        "isbn13": "9788937460777",
        "title": "1984",
        "author": "조지 오웰",
        "publisher": "민음사",
        "published_date": "2003",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9788937460777-L.jpg",
        "description": "감시와 권력이 언어와 생각을 어떻게 지배하는지 묻는 강력한 디스토피아 고전입니다.",
        "category": "문학",
        "sub_category": "디스토피아",
        "rating": 4.7,
        "review_count": 31245,
        "source": "seed",
        "source_url": "",
    },
    {
        "book_id": "seed_search_meaning",
        "isbn13": "9788936811549",
        "title": "죽음의 수용소에서",
        "author": "빅터 프랭클",
        "publisher": "청아출판사",
        "published_date": "2020",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9788936811549-L.jpg",
        "description": "극한의 고통 속에서도 인간이 의미를 발견할 수 있는지를 증언하는 심리학 고전입니다.",
        "category": "심리",
        "sub_category": "의미치료",
        "rating": 4.8,
        "review_count": 27654,
        "source": "seed",
        "source_url": "",
    },
    {
        "book_id": "seed_pachinko",
        "isbn13": "9788974746926",
        "title": "파친코",
        "author": "이민진",
        "publisher": "문학사상",
        "published_date": "2022",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9788974746926-L.jpg",
        "description": "재일 한국인 가족의 삶을 통해 정체성, 생존, 기억의 문제를 깊게 다룹니다.",
        "category": "문학",
        "sub_category": "역사소설",
        "rating": 4.8,
        "review_count": 19867,
        "source": "seed",
        "source_url": "",
    },
    {
        "book_id": "seed_plague",
        "isbn13": "9788937460388",
        "title": "페스트",
        "author": "알베르 카뮈",
        "publisher": "민음사",
        "published_date": "2011",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9788937460388-L.jpg",
        "description": "고난 앞에서 인간이 선택할 수 있는 연대와 책임, 부조리의 태도를 묻는 소설입니다.",
        "category": "철학",
        "sub_category": "실존주의 문학",
        "rating": 4.6,
        "review_count": 14532,
        "source": "seed",
        "source_url": "",
    },
]


def get_seed_books() -> list[dict]:
    return [dict(book) for book in SEED_BOOKS]
